Repository aau-giraf/api_client, pull requests merged in 2020-04, with the labels that each got.

#40 removed as
  test/api/pictogram_api_test.dart
Labels: ReleaseFix

#45 Feature wp267
  lib/models/settings_model.dart
  test/models/settings_model_test.dart
Labels: Gruppe 11

#46 Interfaces for offline added to all models (sorry for late PR)
  api_client.iml
  lib/models/activity_model.dart
  lib/models/department_model.dart
  lib/models/department_name_model.dart
  lib/models/giraf_user_model.dart
  lib/models/model.dart
  lib/models/pictogram_model.dart
  lib/models/settings_model.dart
  lib/models/timer_model.dart
  lib/models/username_model.dart
  lib/models/week_model.dart
  lib/models/week_name_model.dart
  lib/models/week_template_model.dart
  lib/models/week_template_name_model.dart
  lib/models/weekday_color_model.dart
  lib/models/weekday_model.dart
  lib/offline_repository/db_model_factory.dart
  lib/offline_repository/exceptions/not_found.dart
  lib/offline_repository/provider.dart
  lib/offline_repository/repository.dart
  lib/offline_repository/repository_interface.dart
  pubspec.yaml
Labels: Gruppe 14
